#!/bin/bash

# Copy Wiki Content Helper Script
echo "📋 Wiki Content Copy Helper"
echo "=========================="
echo ""

echo "🏠 HOME PAGE CONTENT:"
echo "===================="
echo ""
echo "Copy this content for your Home page:"
echo ""
echo "--- START COPY ---"
cat scripts/wiki_home_page_template.md
echo ""
echo "--- END COPY ---"
echo ""

echo "📋 PRD CONTENT:"
echo "=============="
echo ""
echo "Copy this content for your Product Requirements Document page:"
echo ""
echo "--- START COPY ---"
head -50 docs/getting-started/PRD.md
echo ""
echo "... (copy the rest from docs/getting-started/PRD.md)"
echo ""
echo "--- END COPY ---"
echo ""

echo "📚 MIGRATION CHECKLIST:"
echo "======================="
echo ""
echo "✅ HIGH PRIORITY PAGES TO CREATE:"
echo "  1. Home (copy from above)"
echo "  2. Product-Requirements-Document (copy from docs/getting-started/PRD.md)"
echo "  3. Solar-Heating-System-V3 (copy from docs/user-guides/USER_GUIDE_SOLAR_HEATING_V3.md)"
echo "  4. Home-Assistant-Integration (copy from docs/user-guides/USER_GUIDE_HOME_ASSISTANT.md)"
echo "  5. Troubleshooting-Guide (copy from docs/troubleshooting/TROUBLESHOOTING_GUIDE.md)"
echo ""
echo "✅ MEDIUM PRIORITY PAGES:"
echo "  6. TaskMaster-AI (copy from docs/user-guides/USER_GUIDE_TASKMASTER_AI.md)"
echo "  7. Rate-of-Change-Sensors (copy from docs/user-guides/USER_GUIDE_RATE_OF_CHANGE_SENSORS.md)"
echo "  8. Development-Environment-Setup (copy from docs/getting-started/DEVELOPMENT_ENVIRONMENT_SETUP.md)"
echo "  9. System-Architecture (copy from docs/getting-started/SYSTEM_OVERVIEW.md)"
echo ""
echo "🎯 QUICK SETUP STEPS:"
echo "===================="
echo ""
echo "1. Go to: https://github.com/DonHugo/sun_heat_and_ftx/wiki"
echo "2. Click 'Create the first page'"
echo "3. Title: 'Home'"
echo "4. Copy the Home page content above"
echo "5. Save the page"
echo "6. Repeat for other pages using the checklist above"
echo ""
echo "💡 PRO TIP: Start with Home and PRD pages first!"
echo ""
echo "🚀 Your Wiki will be professional and organized!"
